export const certificates = [
  'IBM Delivery Central Platform Foundations - 2025',
  'AWS Certified Cloud Practitioner - 2025',
  'Banking Industry Jumpstart - 2024',
  'Enterprise Design Thinking Practitioner - 2024',
  'IBM Consulting Way Habits - Foundational - 2024',
  'Full Stack Web Development: HTML, CSS, React and Node',
  'The Complete SQL Bootcamp 2021',
  "Typescript: The Complete Developer's Guide",
  "Next JS: The Complete Developer's Guide",
  'The Complete Node.js Developer Course',
  'React - The Complete Guide 2024',
  'The Complete JavaScript Course 2022',
  'Infosys Certified Mongo Developer',
  'Infosys Certified NodeJs Developer',
  'Infosys Certified React Developer',
  'Infosys Certified Vue Developer',
  'IBMer watsonx Challenge',
];
